---
- name: Playbook
  hosts: all
  become: yes
  tasks: 
  - name: Create nice-script.sh
    copy:
            src: /home/rafa/toomash/plat-eng-task-starter/nice-script.sh
            dest: /etc/skel/nice-script.sh

  - name: Create home dir for john
    ansible.builtin.file:
      path: /better-place
      state: directory

  - name: Create group
    group:
      name: sudoguys
      state: present

  - name: Allow sudo group to have passwordless sudo
    lineinfile:
            dest: /etc/sudoers
            state: present
            regexp: '^%sudoguys'
            line: '%sudoguys ALL=(ALL) NOPASSWD:ALL'
            validate: 'visudo -cf %s'

  - name: Add user john
    ansible.builtin.user:
            name: john
            uid: 1234
            home: /better-place/
            create_home: true
            groups: sudoguys
            append: yes
            state: present

  - name: Update system
    command: sudo apt-get update
  - name: Install apt-file
    command: sudo apt-get install apt-file -y
  - name: Update apt-file
    command: sudo apt-file update
  - name: Install vim
    command: sudo apt-get install vim -y

  - name: Install TMUX
    package:
            name: tmux
            state: present
    tags: tmux
 
  - name: Install wget
    command: sudo apt-get install wget

  - name: Download packages
    ansible.builtin.shell: wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  
  - name: Echo stuff
    ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

  - name: Install python3
    expect:
            command: sudo apt-get install python3.6
            responses:
                    'first prompt': y

  #- name: Install Terraform
  #  expect:
  #          command: sudo apt update && sudo apt install terraform
  #          responses:
  #                  'first prompt': y
